apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-app
  labels:
    app: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: c-app
          image: shestera/scaletestapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
            limits:
              memory: "30Mi"
